kafka:
  topic:
    name: test-topic

# How often should the messages be generated and pushed to Kafka Topic
timer:
  period: 10000
  delay: 10000


quarkus:
  log:
#    category:
#     "org.apache.camel.component.kafka":
#        level: DEBUG

# Kafka brokers in native test
"%prod":
  camel:
    component:
      kafka:
        brokers: ${kafka.bootstrap.servers}
